name: docker-build-and-push

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine Docker tag
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "TAG=latest" >> $GITHUB_OUTPUT
          fi

      # --- Backend Build ---
      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: server
          file: ./server/Dockerfile
          push: true
          tags: |
            doublelayer/snoop-backend:${{ steps.vars.outputs.TAG }}
          cache-from: type=gha,scope=backend
          cache-to: type=gha,mode=max,scope=backend

      # --- Frontend Build ---
      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: client
          file: ./client/Dockerfile
          push: true
          tags: |
            doublelayer/snoop-frontend:${{ steps.vars.outputs.TAG }}
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL }}
            VITE_WS_URL=${{ secrets.VITE_WS_URL }}
          cache-from: type=gha,scope=frontend
          cache-to: type=gha,mode=max,scope=frontend
